DROP TABLE SHOP_TB;
DROP SEQUENCE SHOPSQ;


CREATE SEQUENCE SHOPSQ NOCACHE;

CREATE TABLE SHOP_TB(
	SHOPNO NUMBER PRIMARY KEY,
	WRITER VARCHAR2(200) NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	SERVICE NUMBER NOT NULL,
	CLEAN NUMBER NOT NULL,
	TRAFFIC NUMBER NOT NULL,
	REVISIT VARCHAR2(1) NOT NULL,
	SELGROUP VARCHAR2(1)  NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTRAINT REV_CHK CHECK (REVISIT IN('Y','N')),
	CONSTRAINT GROUP_CHK CHECK (SELGROUP IN('O','F','C','S','E'))
);

SELECT * FROM SHOP_TB ORDER BY SHOPNO DESC;

INSERT INTO SHOP_TB VALUES(
	SHOPSQ.NEXTVAL,
	'BONIK',
	'ALLREVIEW',
	'TEST',
	4.5,4.0,3.0,
	'Y','O',SYSDATE
);



